### ISSUE TITLE
Creating a new file has font-color that matches background

### ISSUE THREAD

**Issue by mfix22** [Yummygum/city-lights-ui-atom#2] opened 2017-11-04 17:44 UTC
<img width="766" alt="screenshot 2017-11-04 10 42 57" src="https://user-images.githubusercontent.com/8397708/32407918-02c25c8c-c14d-11e7-905d-e60388448806.png">

Not able to see what I am typing 😄 Thanks for the awesome theme! I've been looking for something like this.

**Comment by jackreichelt** [comment] 2017-11-05 22:20
![screen shot 2017-11-06 at 9 20 19 am](https://user-images.githubusercontent.com/723717/32419769-bb089482-c2d3-11e7-9673-099b28203937.png)
Same is true for the find and replace boxes.

**Comment by noudadrichem** [comment] 2017-11-07 13:59
Hi @jackreichelt & @mfix22,

Thanks for using the theme and the feedback!
I tried to debug this problem but I couldn't find it. Do you guys overwrite any `color` values in your custom stylesheet in Atom?

Let me know!

**Comment by sherwinWatson** [comment] 2017-11-08 09:52
<img width="1280" alt="screen shot 2017-11-08 at 4 51 49 pm" src="https://user-images.githubusercontent.com/18283056/32542424-286560a0-c4a5-11e7-824e-c0a9c2e9b5f8.png">
same here
no color everwritten

Cool theme btw.

**Comment by mfix22** [comment] 2017-11-09 00:39
I just did a fresh install on a separate machine and it works great. I am going to try and source the root of the problem when I get to my other computer. I don't have customer styles on either computer.

**Comment by noudadrichem** [comment] 2017-11-09 14:06
Hi @mfix22,

This do is very strange, let me know if you find something!

**Comment by sherwinWatson** [comment] 2017-11-10 01:42
@noudadrichem I tried to search the element with developer tool and I think the problem is the y coordinate

<img width="1280" alt="screen shot 2017-11-10 at 8 32 22 am" src="https://user-images.githubusercontent.com/18283056/32638629-caad55a4-c5f2-11e7-8805-6e25a13fc244.png">

It's below the box. Compared to this original theme

<img width="1280" alt="screen shot 2017-11-10 at 8 32 53 am" src="https://user-images.githubusercontent.com/18283056/32638657-e774ac5a-c5f2-11e7-9a20-8f3d9de8a6bf.png">

I found the y coordinate go wrong starting from 
`<div class="line" data-screen-row="0"><span class="null"><span class="syntax--source syntax--js syntax--regexp">holla</span></span></div>`

**Comment by noudadrichem** [comment] 2017-11-11 19:22
Hi,

I patched an update, it should be fixed now.

Let me know.

Sincerely.

**Closed by noudadrichem** 2017-11-11 19:22 UTC

**Comment by sherwinWatson** [comment] 2017-11-12 07:56
It's fixed. kudos to @noudadrichem .
